table ks1months
	isHidden
	lineageTag: 0db292b6-82f5-4185-94a3-d75279fc83da

	column month
		dataType: string
		isHidden
		lineageTag: 2f1be919-3952-43a2-8a58-a31b1b6c4e54
		summarizeBy: none
		sourceColumn: month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: af3b9412-9a79-4af9-b680-0ed04d33c8c7
		summarizeBy: sum
		sourceColumn: Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition ks1months = m
		mode: import
		queryGroup: data
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Data Analysis\Copy of KUKU SPUR DAILY REPORTS-JULY(1).xlsx"), null, true),
				    KS1_Sheet = Source{[Item="KS1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(KS1_Sheet, [PromoteAllScalars=true]),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{"Column1", "week"}, {"Column2", "sunday"}, {"Column3", "monday"}, {"Column4", "tuesday"}, {"Column5", "wednseday"}, {"KUKU SPUR 1-Ngara", "thursday"}, {"Column7", "friday"}, {"Column8", "saturday"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"week", "sunday", "monday", "tuesday", "wednseday", "thursday", "friday", "saturday"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Other Columns", "Index", 0, 1, Int64.Type),
				    #"Filtered Rows" = Table.SelectRows(#"Added Index", each ([week] = null)),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Filtered Rows",{"thursday", "Index"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Other Columns1", each ([thursday] <> null and [thursday] <> "THURSDAY")),
				    #"Renamed Columns1" = Table.RenameColumns(#"Filtered Rows1",{{"thursday", "month"}})
				in
				    #"Renamed Columns1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

